name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:

  test:
    name: Test — Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests with coverage
        run: npm run test:coverage -- --ci --forceExit

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

  # quality:
  #   name: Quality — Type Check & Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: npm

  #     - name: Install dependencies
  #       run: npm ci --legacy-peer-deps

  #     - name: TypeScript — type check
  #       run: npx tsc --noEmit

  #     - name: ESLint — static analysis
  #       run: npm run lint

 

  build:
    name: Build — Next.js
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build production
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8080
        run: npm run build

  # security:
  #   name: Security — Vulnerability Scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: npm

  #     - name: Install dependencies
  #       run: npm ci --legacy-peer-deps

  #     - name: npm audit — known vulnerabilities
  #       run: npm audit --audit-level=high --legacy-peer-deps
  #       continue-on-error: true

  #     - name: Trivy — filesystem CVE scan
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: fs
  #         scan-ref: .
  #         format: table
  #         exit-code: '1'
  #         ignore-unfixed: true
  #         severity: CRITICAL,HIGH
  #         skip-dirs: node_modules/.cache,.next

  #     - name: Dependency Review (pull requests)
  #       if: github.event_name == 'pull_request'
  #       uses: actions/dependency-review-action@v4
  #       with:
  #         fail-on-severity: high
